# ==========================
# Kuavo Unified Config File
# ==========================

hydra:  # Hydra config directory, for parameter checking only
  run:
    dir: ./outputs/kuavo_deploy_hydra_save/singlerun/${now:%Y%m%d_%H%M%S}  # Single run root dir
  sweep:
    dir: ./outputs/kuavo_deploy_hydra_save/multirun/${now:%Y%m%d_%H%M%S}  # sweep root dir
    subdir: ${hydra:job.override_dirname}


# =====================================================
# env config: Real-machine Environment Configuration
# =====================================================
env:
  env_name: Kuavo-Real
  control_mode: joint # joint or eef （eef still under development）
  eef_type: leju_claw
  which_arm: both
  head_init: null
  ros_rate: 10  # Inference speed in Hz

  #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  only_arm: true  # Default is true, whether to use only arm data. Setting this to true automatically ignores all lower limb data.
  #!!!!!!!!!!!!Should be true for all tasks in this competition!!!!!!!!!!!!!!!

  image_size: &IMGSIZE [848, 480]  # Img size: width, height
  depth_range: &DEPTHRANGE [0, 1500]  # Depth imaging range in mm, default=[0,1500]
  obs_key_map:  # Topic, msg type, freq, img size, depth crop. Must be consistent with training config!
    head_cam_h: ["/cam_h/color/image_raw/compressed", "CompressedImage", 30, *IMGSIZE]  # Head RGB img topic, COMPULSORY
    wrist_cam_l: ["/cam_l/color/image_raw/compressed", "CompressedImage", 30, *IMGSIZE]  # Left wrist RGB img topic, choose one between this and below
    wrist_cam_r: ["/cam_r/color/image_raw/compressed", "CompressedImage", 30, *IMGSIZE]  # Left wrist RGB img topic, choose one between this and above
    joint_q: ["/sensors_data_raw", "sensorsData", 500]  # Joint angle topic, COMPULSORY
    # qiangnao: ["/dexhand/state", "JointState", 500]
    leju_claw: ["/leju_claw_state", "lejuClawState", 500]  # End-effector topic for gripper-claw
    # rq2f85: ["/gripper/state", "JointState", 500]
  
  arm_state_keys: ["joint_q","gripper"]  # Do not change. Model observation arm state, with joint angles and gripper state.
  frame_alignment: false  # Frame alignment. default=false
  ratio: 1.0 # With frame alignment, this is the ratio of the latest observation vs all older observations. default=1.0
  
  # Limits joint values. I.e. upper and lower limit definitions. Do not change these.
  limits:
    # joint angle limits (7 joints per arm)
    joint_q:
      min: [-3.14, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14]
      max: [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14]
    
    # Gripper limits
    gripper:
      min: [0, 0]
      max: [1, 1]
    
    # End-effector limits
    eef:
      min: [-1, -1, -1, -3.14, -3.14, -3.14, -1, -1, -1, -3.14, -3.14, -3.14]
      max: [1, 1, 1, 3.14, 3.14, 3.14, 1, 1, 1, 3.14, 3.14, 3.14]
    
    # End-effector relative limits (for delta, currently in development)
    eef_relative:
      min: [-0.005, -0.0075, -0.004, -0.03, -0.03, -0.05, -0.005, -0.0075, -0.004, -0.03, -0.03, -0.05]
      max: [0.005, 0.0075, 0.004, 0.03, 0.03, 0.05, 0.005, 0.0075, 0.004, 0.03, 0.03, 0.05]
    
    # Robot movement limits (x, y, yaw, move_flag)
    base:
      min: [-2.0, -2.0, -3.14, 0]
      max: [2.0, 2.0, 3.14, 1]

  # It is NOT recommended to change these following configs

  # dex_dof_needed is the dof needed for dex hand. The qiangnao dexhand has 6 dof, with fully closed being [100] * 6, fully open being [0] * 6.
  # 1: When precise operation or multi-finger coordinated operation is not required, it is usually set to 1, which means that only the first joint is needed as the basis for opening and closing.
  #    In this case, [0, 100, 0, 0, 0, 0] is used to represent the open state, and [100] * 6 represents the clenched fist state.
  # 2(Untested): 0,2,3,4,5 dof becomes a single dof.
  # 6(Untested): All 6 dof are available.
  qiangnao_dof_needed: 1   # default=1

  is_binary: false  # Is open and close binary? default=false


# =====================================================
# inference config: Change here for inferencing configuration, both in sim and real-device
# =====================================================
inference:
  go_bag_path: /path/to/your/go.bag  #! ! ! Temporarily not used in the competition emulator! ! ! , the complete path of the bag needs to be provided during real-machine inference, such as reaching the pre-grab posture, etc. You can directly copy a trained rosbag control.
  policy_type: "lingbot"  #Strategy name, supports diffusion, act, lingbot, etc.
  pretrained_path: "/root/kuavo_data_challenge/artifacts/lingbot/run_20260703_113523/checkpoints/global_step_141675/hf_ckpt"
  eval_episodes: 3
  seed: 42  #Random seeds can be used to fix the initial state of each object in simulation to facilitate reproduction.
  start_seed: 42  #The random seed at the beginning of the round can be used to fix the initial state of each object in the simulation to facilitate reproduction.
  device: "cuda"  # or "cpu"
  task: "r2"
  method: "lingbot_task2_epoch1"
  timestamp: "run_20260703_113523"
  epoch: best  #Which epoch to use for training saving, you can fill in 50, 100, best, etc. Note: the code will load the model parameters of the policy in outputs/train/<task>/<method>/<timestamp>/epoch<epoch>
  max_episode_steps: 2000

  #Effective when policy_type=lingbot
  lingbot_root: "/root/kuavo_data_challenge/third_party/lingbot-vla"
  qwen25_path: "/root/kuavo_data_challenge/artifacts/lingbot/qwen25_runtime"
  task_prompt: "Sorting sleeves by weight"
  lingbot_use_length: 5
  lingbot_chunk_ret: false
  lingbot_norm_stats_file: "/root/kuavo_data_challenge/assets/norm_stats/task2_supertrimmed_200.json"
  lingbot_data_type: "customized"
  lingbot_execute_raw_action: false
