# syntax=docker/dockerfile:1.7

FROM nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04@sha256:2d913b09e6be8387e1a10976933642c73c840c0b735f0bf3c28d97fc9bc422e0
COPY --from=ghcr.io/astral-sh/uv:0.5.1 /uv /uvx /bin/

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential clang git git-lfs linux-headers-generic && \
    rm -rf /var/lib/apt/lists/*

ENV UV_LINK_MODE=copy \
    UV_PROJECT_ENVIRONMENT=/.venv \
    OPENPI_DATA_HOME=/openpi_assets \
    IS_DOCKER=true

RUN uv venv --python 3.11.9 "${UV_PROJECT_ENVIRONMENT}"

COPY third_party/openpi-kuavo/uv.lock third_party/openpi-kuavo/pyproject.toml ./
COPY third_party/openpi-kuavo/packages/openpi-client/pyproject.toml packages/openpi-client/pyproject.toml
COPY third_party/openpi-kuavo/packages/openpi-client/src packages/openpi-client/src
RUN --mount=type=cache,target=/root/.cache/uv \
    GIT_LFS_SKIP_SMUDGE=1 uv sync --frozen --no-install-project --no-dev

COPY third_party/openpi-kuavo/ ./
RUN --mount=type=cache,target=/root/.cache/uv \
    GIT_LFS_SKIP_SMUDGE=1 uv sync --frozen --no-dev && \
    /.venv/bin/python -c "import transformers; print(transformers.__file__)" | \
        xargs dirname | \
        xargs -I{} cp -r src/openpi/models_pytorch/transformers_replace/. {}

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["exec uv run scripts/serve_policy.py $SERVER_ARGS"]
